---
- name: Check if variable is defined
  debug:
    msg: "tower_user_accounts  is not defined"
  when:
      - tower_user_accounts is not defined


- name: Add tower user
  tower_user:
     username: "{{ user.user }}"
     password: "{{ user.password | default('change_me') }}"
     email: "{{ user.email | default('rhpds-admins@redhat.com') }}"
     first_name: "{{ user.firstname | default(user.user) }}"
     last_name: "{{ user.lastname | default(user.user) }}"
     superuser: "{{ user.superuser | default('no')}}"
     state: present
     tower_host: "{{ tower_hostname }}"
     tower_username: "{{ tower_admin_username | default('admin') }}"
     tower_password: "{{ tower_admin_password }}"
     tower_verify_ssl: "{{ tower_verify_ssl | default(false) }}"
  loop: "{{ tower_user_accounts }}"
  loop_control:
    loop_var: user
  when: tower_user_accounts is defined
  tags:
    - tower-user-create
